spring.application.name=cloud-cost-dashboard
# In-Memory H2 Database (Default)
spring.datasource.url=jdbc:h2:mem:cloudcostdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# MySQL Database Configurations (Commented out)
# spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cloudcostdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
# spring.datasource.username=${DB_USER:root}
# spring.datasource.password=${DB_PASSWORD:password}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configurations
app.jwt.secret=${JWT_SECRET:3cfa76f4e15647a7f45b53e7f45c531548e6587c88a8f1542cfcdbb3522f2b3e}
# 1 day expiration in ms
app.jwt.expiration=86400000

# Mock Toggle
app.use-mock-data=${USE_MOCK_DATA:true}
# CORS Allowed Origins
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
