spring.application.name=cloud-cost-dashboard

# MySQL Database Configurations (Commented out)
spring.datasource.url=jdbc:mysql://localhost:3306/cloudcostdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Karishm@08
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configurations
app.jwt.secret=${JWT_SECRET:3cfa76f4e15647a7f45b53e7f45c531548e6587c88a8f1542cfcdbb3522f2b3e}
# 1 day expiration in ms
app.jwt.expiration=86400000

# Mock Toggle
app.use-mock-data=${USE_MOCK_DATA:true}
# CORS Allowed Origins
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
